### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by HappyDay-design** [jianfeng123/deeplearning_for_single_traffic_light#1]
Thank you for sharing

I get errors when running your models
Could you please upload papers related to these models?
![image](https://user-images.githubusercontent.com/82990411/192086490-ef8eb280-d21a-413d-bdb4-114417a8c5df.png)
only one figure is shown in `main_for_DQN.py`

**Comment by HappyDay-design** [comment]
In `main_for_PPO.py`
Traceback (most recent call last):
  File "/home/osboxes/Desktop/deeplearning_for_single_traffic_light/traffic_control/main_for_PPO.py", line 129, in <module>
    run_main()
  File "/home/osboxes/Desktop/deeplearning_for_single_traffic_light/traffic_control/main_for_PPO.py", line 127, in run_main
    traffic_train()
  File "/home/osboxes/Desktop/deeplearning_for_single_traffic_light/traffic_control/main_for_PPO.py", line 61, in traffic_train
    a = ppo.choose_action(s,a_before)
  File "/home/osboxes/Desktop/deeplearning_for_single_traffic_light/traffic_control/DRLmodel/PPO.py", line 111, in choose_action
    s = np.reshape(s, newshape=[1, self.road_size, self.road_size, 2])
  File "<__array_function__ internals>", line 6, in reshape
  File "/home/osboxes/anaconda3/envs/TF1/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/osboxes/anaconda3/envs/TF1/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/home/osboxes/anaconda3/envs/TF1/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 1 into shape (1,48,48,2)
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error)
